# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

name: "🧪 MOSIP mock: Build and publish Docker image"

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ github.repository }}-mock